services:

  site:
    container_name: laravel
    hostname: laravel
    depends_on:
      - db
    build:
      context: .
      dockerfile: bak.origD
    working_dir: /var/app/current

#  HOST_PORT and CONTAINER_PORT.
#  the HOST_PORT is ${PORT} and the container port is 80
#  Networked service-to-service communication uses the CONTAINER_PORT.
#  When HOST_PORT is defined, the service is accessible outside the swarm as well.
    ports:
      - ${PORT}:80
    expose:
      - ${DEBUG_PORT}
    stdin_open: true
    tty: true
    volumes:
      - "./:/var/app/current"
    command: sh -c "bash /var/app/current/docker_init.sh"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    container_name: db_laravel
    restart: "no"
    build:
      context: "mysql"
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/dbdata:/var/lib/mysql
      - ./mysql:/app
volumes:
  dbdata:
